spring:
  datasource:
    url: jdbc:mysql://localhost:3306/${db.name}?autoReconnect=true&useSSL=false
    username: root
    password: password
logging:
  level:
    org:
      springframework:
        security: INFO

server:
  port: ${server.port}
